Feature sort filter
CDCgov/data-exchange-processing-status pull request #148
Opened 2024-08-01 14:15 UTC by mtammineni

Added sort and filter functionality to the getUploadStatus api

2024-08-01 21:18 UTC, mkrystof requested changes

2024-08-01 21:18 UTC, mkrystof commented on pstatus-graphql-ktor/src/main/kotlin/gov/cdc/ocio/processingstatusapi/loaders/UploadStatusLoader.kt
> +                        submissionDate:String?
Do we need to add `submissionDate`?  We already have dateStart and dateEnd.

2024-08-01 21:18 UTC, mkrystof commented on pstatus-graphql-ktor/src/main/kotlin/gov/cdc/ocio/processingstatusapi/loaders/UploadStatusLoader.kt
> +        submissionDate?.run {
I think the `submissionDate` filter can be removed - redundant.

2024-08-02 13:15 UTC, mkrystof approved these changes

2024-08-02 13:21 UTC, mtammineni commented
Sort and Filter for UploadStatus

2024-08-02 17:04 UTC, mtammineni commented
Sort and Filter

2024-08-02 17:38 UTC, mtammineni commented
Sort and Filter

2024-08-02 17:39 UTC, mtammineni commented
Sort and filter

2024-08-02 17:53 UTC, mtammineni commented
Sort and Filter

2024-08-02 17:53 UTC, merged